name: Report Breaking Changes
author: Tyler Miller
description: Automatically update an issue and/or discussion with breaking changes.

runs:
  using: node16
  main: index.js
branding:
  icon: cast
  color: red

inputs:
  token:
    description: The token used for posting the comments (e.g. `github.token`).
    required: true
  issueNumber:
    description: >
      Issue to comment on for each breaking change commit found.
      May be combined with `discussionNumber`.
      (`integer`)
    required: false
    default: ''
  discussionNumber:
    description: >
      Discussion to comment on for each breaking change commit found.
      May be combined with `issueNumber`.
      (`integer`)
    required: false
    default: ''
  headerLevel:
    description: >
      Header level for the commit message title/subject (use `false` to
      disable header styling of commit title).
      (`1|2|3|4|5|6|false`)
    required: false
    default: 3

outputs:
  found:
    description: Whether a breaking change was detected. (`boolean`)
